  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt/data:/app/data
    devices:
      - ${ZIGBEE_COORDINATOR_PORT}:${ZIGBEE_COORDINATOR_PORT}
    ports:
      - "8080:8080"
    networks:
      - proxy
